delete
from top_movies
where movie_id > 0;

create table if not exists uniq_movie_id
(
    id       bigint generated by default as identity primary key,
    movie_id bigint,
    average  double precision
);

insert into uniq_movie_id (movie_id)
select distinct movie_id
from score;

do
$do$
    declare
        mi  bigint;
        avg int;
    begin
        for count in 1..(select count(*) from uniq_movie_id)
            loop
                mi = movie_id from uniq_movie_id umi where umi.id = count;
                avg = avg(score) from score where movie_id = mi;
                if (select count(movie_id)
                    from score
                    where movie_id = mi) >= 20
                then
                    update uniq_movie_id set average = avg where id = count;
                else
                    delete from uniq_movie_id where id = count;
                end if;
            end loop;
    end;
$do$;

insert into top_movies (rating, movie_id)
select round(average), movie_id
from uniq_movie_id
order by average desc
limit 50;

drop table uniq_movie_id;
